source 'https://rubygems.org'

gem 'brstring'
gem 'correios-cep'
gem 'cpf_faker'
gem 'cucumber'
gem 'faker'
gem 'httparty'
gem 'logger'
gem 'parallel_tests'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-checkstyle_formatter'
