casasbahia:
  dev:
    departamento: 'TODO:'
    conteudos: 'TODO:'
    login: 'TODO:'
    carrinho: 'TODO:'
  stg:
    departamento: 'TODO:'
    conteudos:
    login: 'TODO:'
    carrinho: 'TODO:'
  prd:
    departamento:
    conteudos:
    login:
    carrinho:

pontofrio:
  dev:
    departamento: 'TODO:'
    conteudos: 'TODO:'
    login: 'TODO:'
    carrinho: 'TODO:'

  stg:
    departamento: 'TODO:'
    conteudos:
    login: 'TODO:'
    carrinho: 'TODO:'

  prd:
    departamento:
    conteudos:
    login:
    carrinho: 